version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ai_studio_postgres
    environment:
      POSTGRES_USER: ai_studio_user
      POSTGRES_PASSWORD: ai_studio_pass
      POSTGRES_DB: ai_studio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ai_studio_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai_studio_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ai_studio_user:ai_studio_pass@postgres:5432/ai_studio_db
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

volumes:
  postgres_data:


