services:
  # FastAPI Backend Service
  - type: web
    name: ai-studio-backend
    env: python
    region: oregon  # or singapore for Asia
    plan: free  # Change to 'starter' for $7/month (no cold starts)
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt && mkdir -p assets/models assets/looks assets/links"
    startCommand: "python3 start_production.py"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Database URL (auto-set from database service below)
      - key: DATABASE_URL
        fromDatabase:
          name: ai-studio-db
          property: connectionString
      
      # These need to be added manually in Render dashboard
      # (marked as sync: false means not stored in this file)
      - key: GOOGLE_CLIENT_ID
        sync: false
      
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      - key: JWT_SECRET_KEY
        sync: false
      
      - key: JWT_ALGORITHM
        value: HS256
      
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      
      - key: FIRST_ADMIN_EMAIL
        sync: false
      
      # Video Generation - NEW (Required for video generation feature)
      - key: GOOGLE_API_KEY
        sync: false
        description: "Google GenAI API key for Veo 3.1 video generation"
      
      - key: REDIS_URL
        sync: false
        description: "Redis connection URL for Celery worker queue (e.g., redis://localhost:6379/0 or external Redis service)"
      
      # Cloudinary - NEW (Required for video/image storage in production)
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      
      - key: CLOUDINARY_API_KEY
        sync: false
      
      - key: CLOUDINARY_API_SECRET
        sync: false
      
      - key: USE_CLOUDINARY
        value: "true"
        description: "Enable Cloudinary storage for videos and images"
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy settings
    autoDeploy: true  # Auto-deploy when you push to main branch

  # Celery Background Worker Service
  - type: worker
    name: ai-studio-celery-worker
    env: python
    region: oregon  # Same region as backend
    plan: free  # Change to 'starter' for $7/month
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "celery -A app.core.celery_app worker --loglevel=info --pool=solo"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Database URL (same as backend)
      - key: DATABASE_URL
        fromDatabase:
          name: ai-studio-db
          property: connectionString
      
      # All same env vars as backend (copy from above)
      - key: GOOGLE_API_KEY
        sync: false
      
      - key: REDIS_URL
        sync: false
      
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      
      - key: CLOUDINARY_API_KEY
        sync: false
      
      - key: CLOUDINARY_API_SECRET
        sync: false
      
      - key: USE_CLOUDINARY
        value: "true"
      
      - key: JWT_SECRET_KEY
        sync: false
      
      - key: JWT_ALGORITHM
        value: HS256
      
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      
      - key: GOOGLE_CLIENT_ID
        sync: false
      
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      - key: FIRST_ADMIN_EMAIL
        sync: false

# PostgreSQL Database
databases:
  - name: ai-studio-db
    databaseName: ai_studio
    user: ai_studio_user
    plan: free  # Change to 'starter' for $7/month (includes backups)

