services:
  # FastAPI Backend Service
  - type: web
    name: ai-studio-backend
    env: python
    region: oregon  # or singapore for Asia
    plan: free  # Change to 'starter' for $7/month (no cold starts)
    buildCommand: "pip install -r requirements.txt && mkdir -p assets/models assets/looks"
    startCommand: "python start_production.py"
    
    # Environment variables
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      
      # Database URL (auto-set from database service below)
      - key: DATABASE_URL
        fromDatabase:
          name: ai-studio-db
          property: connectionString
      
      # These need to be added manually in Render dashboard
      # (marked as sync: false means not stored in this file)
      - key: GOOGLE_CLIENT_ID
        sync: false
      
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      - key: JWT_SECRET_KEY
        sync: false
      
      - key: JWT_ALGORITHM
        value: HS256
      
      - key: JWT_ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      
      - key: JWT_REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      
      - key: FIRST_ADMIN_EMAIL
        sync: false
    
    # Health check
    healthCheckPath: /health
    
    # Auto-deploy settings
    autoDeploy: true  # Auto-deploy when you push to main branch

# PostgreSQL Database
databases:
  - name: ai-studio-db
    databaseName: ai_studio
    user: ai_studio_user
    plan: free  # Change to 'starter' for $7/month (includes backups)

